import{a as v,S as E,i as s}from"./assets/vendor-xpOxgMII.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",M="54417407-1c43465e9e8135d46dad72044",$=15;async function f(t,r){const i={key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:$},{data:a}=await v.get(q,{params:i});return a}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new E(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const r=t.map(({webformatURL:i,largeImageURL:a,tags:e,likes:o,views:c,comments:S,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${i}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${c}</p>
          <p><b>Comments</b> ${S}</p>
          <p><b>Downloads</b> ${P}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),B.refresh()}function A(){m.innerHTML=""}function p(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}function L(){y.classList.remove("is-hidden")}function l(){y.classList.add("is-hidden")}const w=document.querySelector(".search-form"),O=document.querySelector(".load-more");let d="",n=1,u=0;const _=15;w.addEventListener("submit",x);O.addEventListener("click",D);async function x(t){if(t.preventDefault(),d=t.currentTarget.elements["search-text"].value.trim(),!d){s.error({message:"Please enter a search query."});return}n=1,u=0,A(),l(),p();try{const r=await f(d,n);if(!r.hits.length){s.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(r.hits),u=Math.ceil(r.totalHits/_),n<u?L():(l(),s.info({message:"We're sorry, but you've reached the end of search results."}))}catch{s.error({message:"Something went wrong. Please try again later."})}finally{b(),w.reset()}}async function D(){n+=1,l(),p();try{const t=await f(d,n);if(!t.hits.length){l(),s.info({message:"We're sorry, but you've reached the end of search results."});return}g(t.hits),G(),n<u?L():(l(),s.info({message:"We're sorry, but you've reached the end of search results."}))}catch{s.error({message:"Something went wrong. Please try again later."})}finally{b()}}function G(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
